# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.network_api import NetworkApi


class TestNetworkApi(unittest.TestCase):
    """ NetworkApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.network_api.NetworkApi()

    def tearDown(self):
        pass

    def test_create_network(self):
        """
        Test case for create_network

        Creates a new network.
        """
        pass

    def test_delete_network(self):
        """
        Test case for delete_network

        Deletes a network.
        """
        pass

    def test_get_all_networks(self):
        """
        Test case for get_all_networks

        Returns all existing networks.
        """
        pass

    def test_get_network_by_id(self):
        """
        Test case for get_network_by_id

        Returns a network.
        """
        pass

    def test_update_network(self):
        """
        Test case for update_network

        Updates a Network.
        """
        pass


if __name__ == '__main__':
    unittest.main()
