# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import epm_client
from epm_client.rest import ApiException
from epm_client.apis.worker_api import WorkerApi
from epm_client.models import Worker


class TestWorkerApi(unittest.TestCase):
    """ WorkerApi unit test stubs """

    def setUp(self):
        self.api = epm_client.apis.worker_api.WorkerApi()

    def tearDown(self):
        pass

    def test_delete_worker(self):
        """
        Test case for delete_worker

        Deletes a Resource Group.
        """
        self.api.delete_worker(id="2b99ba90-ed38-4ec1-bfe7-de0db3008aa4")
        pass

    def test_get_all_workers(self):
        """
        Test case for get_all_workers

        Returns all registered workers
        """
        print(self.api.get_all_workers())
        pass

    def test_install_adapter(self):
        """
        Test case for install_adapter

        Sets up the specified worker to install the specified type of adapter.
        """
        self.api.install_adapter(id="277c254a-6395-4d1e-96a5-2d992a39222d", type="docker")
        pass

    def test_register_worker(self):
        """
        Test case for register_worker

        Registers the worker and saves the information.
        """
        w = Worker(ip="192.168.161.162", user="ubuntu", passphrase="", password="", epm_ip="10.147.65.145", keyname="mykey")
        self.api.register_worker(w)
        pass


if __name__ == '__main__':
    unittest.main()
