# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import epm_client
from epm_client.rest import ApiException
from epm_client.apis.tosca_api import TOSCAApi


class TestTOSCAApi(unittest.TestCase):
    """ TOSCAApi unit test stubs """

    def setUp(self):
        self.api = epm_client.apis.tosca_api.TOSCAApi()

    def tearDown(self):
        pass

    def test_deploy_tosca_template(self):
        """
        Test case for deploy_tosca_template

        Deploys a Tosca template.
        """
        service_template = open("resources/service_template.yaml")
        self.api.deploy_tosca_template(service_template.read())
        service_template.close()
        pass


if __name__ == '__main__':
    unittest.main()
