# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.runtime_api import RuntimeApi


class TestRuntimeApi(unittest.TestCase):
    """ RuntimeApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.runtime_api.RuntimeApi()

    def tearDown(self):
        pass

    def test_download_file_from_instance(self):
        """
        Test case for download_file_from_instance

        Downloads a file from a VDU.
        """
        pass

    def test_execute_on_instance(self):
        """
        Test case for execute_on_instance

        Executes given command on the given VDU.
        """
        pass

    def test_start_instance(self):
        """
        Test case for start_instance

        Starts the given VDU.
        """
        pass

    def test_stop_instance(self):
        """
        Test case for stop_instance

        Stops the given VDU.
        """
        pass

    def test_upload_file_to_instance_by_file(self):
        """
        Test case for upload_file_to_instance_by_file

        Uploads a file to a VDU.
        """
        pass

    def test_upload_file_to_instance_by_path(self):
        """
        Test case for upload_file_to_instance_by_path

        Uploads a file to a VDU.
        """
        pass


if __name__ == '__main__':
    unittest.main()
