# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import epm_client
from epm_client.rest import ApiException
from epm_client.apis.key_api import KeyApi


class TestKeyApi(unittest.TestCase):
    """ KeyApi unit test stubs """

    def setUp(self):
        self.api = epm_client.apis.key_api.KeyApi()

    def tearDown(self):
        pass

    def test_add_key(self):
        """
        Test case for add_key

        Uploads a key to the EPM.
        """
        pass

    def test_delete_key(self):
        """
        Test case for delete_key

        Deletes a Key.
        """
        self.api.delete_key(id="8486fea1-b334-4c5d-8eed-8745bf04dcb1")
        pass

    def test_get_all_keys(self):
        """
        Test case for get_all_keys

        Returns all available Keys
        """
        print(self.api.get_all_keys())
        pass


if __name__ == '__main__':
    unittest.main()
