# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.resource_group_api import ResourceGroupApi


class TestResourceGroupApi(unittest.TestCase):
    """ ResourceGroupApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.resource_group_api.ResourceGroupApi()

    def tearDown(self):
        pass

    def test_create_resource_group(self):
        """
        Test case for create_resource_group

        Creates a new Resource Group.
        """
        pass

    def test_delete_resource_group(self):
        """
        Test case for delete_resource_group

        Deletes a Resource Group.
        """
        pass

    def test_get_all_resource_groups(self):
        """
        Test case for get_all_resource_groups

        Returns all Resource Groups.
        """
        pass

    def test_get_resource_group_by_id(self):
        """
        Test case for get_resource_group_by_id

        Returns a Resource Group.
        """
        pass

    def test_update_resource_group(self):
        """
        Test case for update_resource_group

        Updates a ResourceGroup.
        """
        pass


if __name__ == '__main__':
    unittest.main()
