# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.po_p_api import PoPApi


class TestPoPApi(unittest.TestCase):
    """ PoPApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.po_p_api.PoPApi()

    def tearDown(self):
        pass

    def test_get_all_po_ps(self):
        """
        Test case for get_all_po_ps

        Returns all PoPs.
        """
        pass

    def test_get_po_p_by_id(self):
        """
        Test case for get_po_p_by_id

        Returns a PoP.
        """
        pass

    def test_register_po_p(self):
        """
        Test case for register_po_p

        Registers a new PoP
        """
        pass

    def test_unregister_po_p(self):
        """
        Test case for unregister_po_p

        Unregisters a PoP.
        """
        pass

    def test_update_po_p(self):
        """
        Test case for update_po_p

        Updates a PoP.
        """
        pass


if __name__ == '__main__':
    unittest.main()
