# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import epm_client
from epm_client.rest import ApiException
from epm_client.apis.vdu_api import VDUApi
from epm_client.models import VDU


class TestVDUApi(unittest.TestCase):
    """ VDUApi unit test stubs """

    def setUp(self):
        self.api = epm_client.apis.vdu_api.VDUApi()

    def tearDown(self):
        pass

    def test_delete_vdu(self):
        """
        Test case for delete_vdu

        Terminates a VDU.
        """
        self.api.delete_vdu("0342b850-6766-4608-a2d3-49dfbd71bf6f")
        pass

    def test_deploy_vdu(self):
        """
        Test case for deploy_vdu

        Allocates resources in the target cloud.
        """
        vdu = VDU(name="test-vdu", image_name="ubuntu", net_name="test-network", po_p_name="test")
        self.api.deploy_vdu(vdu.to_dict())
        pass

    def test_get_all_vdus(self):
        """
        Test case for get_all_vdus

        Returns all VDUs.
        """
        self.api.get_all_vdus()
        pass

    def test_get_vdu_by_id(self):
        """
        Test case for get_vdu_by_id

        Returns a VDU.
        """
        self.api.get_vdu_by_id("843a5753-fa80-41de-9c46-cb8d9754a97f")
        pass

    def test_update_vdu(self):
        """
        Test case for update_vdu

        Updates a VDU.
        """
        pass


if __name__ == '__main__':
    unittest.main()
