# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import os
import sys
from setuptools import setup, find_packages

# Utility function to read the README file.
# Used for the long_description.  It's nice, because now 1) we have a top level
# README file and 2) it's easier to type in the README file than to put a raw
# string in below ...

def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name='epm_client',
    version='1.0.1-SNAPSHOT',
    description="EPM REST API",
    author_email="michael.pauls@tu-berlin.de",
    url="https://github.com/tub-elastest/epm-client-python",
    keywords=["Swagger", "Python", "EPM REST Client"],
    install_requires=[],
    packages=find_packages(exclude=['docs','test']),
    include_package_data=True,
    long_description=read('README.md')
)
