# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import epm_client
from epm_client.rest import ApiException
from epm_client.models.network import Network


class TestNetwork(unittest.TestCase):
    """ Network unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetwork(self):
        """
        Test Network
        """
        model = epm_client.models.network.Network()


if __name__ == '__main__':
    unittest.main()
