# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import epm_client
from epm_client.rest import ApiException
from epm_client.models.vdu import VDU


class TestVDU(unittest.TestCase):
    """ VDU unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVDU(self):
        """
        Test VDU
        """
        model = epm_client.models.vdu.VDU()


if __name__ == '__main__':
    unittest.main()
