# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FileUploadBody(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, remote_path=None, host_path=None):
        """
        FileUploadBody - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'remote_path': 'str',
            'host_path': 'str'
        }

        self.attribute_map = {
            'remote_path': 'remotePath',
            'host_path': 'hostPath'
        }

        self._remote_path = remote_path
        self._host_path = host_path

    @property
    def remote_path(self):
        """
        Gets the remote_path of this FileUploadBody.

        :return: The remote_path of this FileUploadBody.
        :rtype: str
        """
        return self._remote_path

    @remote_path.setter
    def remote_path(self, remote_path):
        """
        Sets the remote_path of this FileUploadBody.

        :param remote_path: The remote_path of this FileUploadBody.
        :type: str
        """
        if remote_path is None:
            raise ValueError("Invalid value for `remote_path`, must not be `None`")

        self._remote_path = remote_path

    @property
    def host_path(self):
        """
        Gets the host_path of this FileUploadBody.

        :return: The host_path of this FileUploadBody.
        :rtype: str
        """
        return self._host_path

    @host_path.setter
    def host_path(self, host_path):
        """
        Sets the host_path of this FileUploadBody.

        :param host_path: The host_path of this FileUploadBody.
        :type: str
        """
        if host_path is None:
            raise ValueError("Invalid value for `host_path`, must not be `None`")

        self._host_path = host_path

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FileUploadBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
