# coding: utf-8

"""
    EPM REST API

    REST API description of the ElasTest Platform Manager Module.

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ResourceGroup(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, vdus=None, networks=None, pops=None):
        """
        ResourceGroup - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'vdus': 'list[VDU]',
            'networks': 'list[Network]',
            'pops': 'list[PoP]'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'vdus': 'vdus',
            'networks': 'networks',
            'pops': 'pops'
        }

        self._id = id
        self._name = name
        self._vdus = vdus
        self._networks = networks
        self._pops = pops

    @property
    def id(self):
        """
        Gets the id of this ResourceGroup.

        :return: The id of this ResourceGroup.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ResourceGroup.

        :param id: The id of this ResourceGroup.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ResourceGroup.

        :return: The name of this ResourceGroup.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ResourceGroup.

        :param name: The name of this ResourceGroup.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def vdus(self):
        """
        Gets the vdus of this ResourceGroup.

        :return: The vdus of this ResourceGroup.
        :rtype: list[VDU]
        """
        return self._vdus

    @vdus.setter
    def vdus(self, vdus):
        """
        Sets the vdus of this ResourceGroup.

        :param vdus: The vdus of this ResourceGroup.
        :type: list[VDU]
        """
        if vdus is None:
            raise ValueError("Invalid value for `vdus`, must not be `None`")

        self._vdus = vdus

    @property
    def networks(self):
        """
        Gets the networks of this ResourceGroup.

        :return: The networks of this ResourceGroup.
        :rtype: list[Network]
        """
        return self._networks

    @networks.setter
    def networks(self, networks):
        """
        Sets the networks of this ResourceGroup.

        :param networks: The networks of this ResourceGroup.
        :type: list[Network]
        """

        self._networks = networks

    @property
    def pops(self):
        """
        Gets the pops of this ResourceGroup.

        :return: The pops of this ResourceGroup.
        :rtype: list[PoP]
        """
        return self._pops

    @pops.setter
    def pops(self, pops):
        """
        Sets the pops of this ResourceGroup.

        :param pops: The pops of this ResourceGroup.
        :type: list[PoP]
        """

        self._pops = pops

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ResourceGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
